/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import static GUIs.CreacionProceso.colaprocesos;
import Objetos.Proceso;

/**
 *
 * @author nelsoncarrillo
 */
public class IOBound extends javax.swing.JFrame {
    private CreacionProceso inty;
    private int instruc;
    private String name; 
    private int prio;
    private Simulacion sim;
    /**
     * Creates new form IOBound
     * @param inty
     */
    public IOBound(CreacionProceso intey,String name,int instruc,int prio) {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        inty = intey;
        this.instruc = instruc;
        this.name = name;
        this.prio=prio;
    }
    
    public IOBound(Simulacion simss,CreacionProceso intey,String name,int instruc,int prio) {
        initComponents();
        setVisible(true);
        this.sim = simss;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        inty = intey;
        this.instruc = instruc;
        this.name = name;
        this.prio=prio;
    }

    private IOBound() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ciclosexcepcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cicloscompletar = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N° de ciclos para realizar una excepción");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 71, -1, -1));
        getContentPane().add(ciclosexcepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 91, 109, -1));

        jLabel2.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N° de ciclos para completar dicha excepción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 132, -1, -1));

        cicloscompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cicloscompletarActionPerformed(evt);
            }
        });
        getContentPane().add(cicloscompletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 158, 105, -1));

        save.setText("Guardar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 225, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIsImages/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cicloscompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cicloscompletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cicloscompletarActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int ciclose = Integer.parseInt(this.ciclosexcepcion.getText());
        int ciclosc =Integer.parseInt(this.cicloscompletar.getText());
        Proceso ele = new Proceso(this.name,this.instruc,"I/O Bound",this.prio,ciclose,ciclosc);
        System.out.println("se agrego io bound");
        if(this.sim!=null){
            this.sim.actualizarListos(ele);
        }else{
                    colaprocesos.agregar(ele);
        }
        inty.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IOBound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IOBound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IOBound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IOBound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IOBound().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cicloscompletar;
    private javax.swing.JTextField ciclosexcepcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
