/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import Objetos.EstadoSimulacion;
import com.google.gson.Gson;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author nelsoncarrillo
 */
public class NumProcesadores extends javax.swing.JFrame {
    
    private Load carga;
    private int cicloreloj;
    private int numcpu;

    /**
     * Creates new form NumProcesadores
     */
    public NumProcesadores(Load c) {
        this.carga=c;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    private NumProcesadores() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public int getCPU(){
        return Integer.parseInt(cpus.getText());
    }
    
    public int getDuracion(){
        return Integer.parseInt(duracion.getText());
    }
    
    public void restablecerEstado(String rutaArchivo) {
        Gson gson = new Gson();

        try (FileReader reader = new FileReader(rutaArchivo)) {
            // Deserializar el archivo JSON al objeto EstadoSimulacion
            EstadoSimulacion estado = gson.fromJson(reader, EstadoSimulacion.class);

           /* // Restaurar los valores en la simulación
            Semaforo semaf = estado.getSemaforo();
            Cola colaL = estado.getColaListos();
            Cola colaT = estado.getColaTerminados();
            Cola colaB = estado.getColaBloqueados();
            int cicloreloj = estado.getCicloReloj();
            int numcpu = estado.getNumProcesadores();
            String pl = estado.getPolitica();
            
            if(numcpu==2){
                Simulacion sim = new Simulacion(pl,cicloreloj, numcpu,colaL,colaB,colaT,estado.getEn1(),estado.getEn2(),semaf);
                return sim;
            }else{
                Simulacion sim = new Simulacion(pl,cicloreloj,numcpu,colaL,colaB,colaT,estado.getEn1(),estado.getEn2(),estado.getEn3(),semaf);
                return sim;
            }

            
            /*if (this.numcpu >= 2) {
                this.cpu1.setProcesoActual(estado.getEn1());
                this.cpu2.setProcesoActual(estado.getEn2());
            }
            if (this.numcpu >= 3) {
                this.cpu3.setProcesoActual(estado.getEn3());
            }*/
            //this.actualizarListos();
            cicloreloj = estado.getCicloReloj();
            numcpu = estado.getNumProcesadores();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cpus = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        duracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Beirut", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número de Procesadores Activos:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        cpus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        getContentPane().add(cpus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 136, -1));

        confirm.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N
        confirm.setText("Confirmar");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jButton1.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Beirut", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Duración del ciclo de reloj:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        duracion.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        getContentPane().add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 130, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("millis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jButton2.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N
        jButton2.setText("Reutilizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIsImages/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        carga.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        Simulacion sim = new Simulacion("FCFS",this.getCPU(),this.getDuracion());
        CreacionProceso l = new CreacionProceso(sim,this.getCPU(),this.getDuracion());
        sim.setVisible(true);
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_confirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.restablecerEstado("test//simulacion.json");
         Simulacion sim = new Simulacion("FCFS",numcpu,cicloreloj);
        CreacionProceso l = new CreacionProceso(sim,numcpu,cicloreloj);
        sim.setVisible(true);
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumProcesadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumProcesadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumProcesadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumProcesadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NumProcesadores().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JTextField cpus;
    private javax.swing.JTextField duracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
